param(
	[string]$GodotExe = "",
	[string]$OutputRoot = "",
	[switch]$SkipProtocolProbe
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ScanRoots = @(
	"scripts",
	"autoload",
	"data",
	"scenes",
	"tools/templates",
	"extensions"
)

function Resolve-ScanPath {
	param([string]$Path)
	return Join-Path $ProjectRoot $Path
}

function Invoke-Rg {
	param(
		[string]$Pattern,
		[string[]]$Roots,
		[switch]$Regex
	)

	$ResolvedRoots = @($Roots | ForEach-Object { Resolve-ScanPath $_ })
	$Args = @("--line-number", "--color", "never")
	if (-not $Regex) {
		$Args += "--fixed-strings"
	}
	$Args += "--"
	$Args += $Pattern
	$Args += $ResolvedRoots
	$Output = & rg @Args 2>$null
	$ExitCode = $LASTEXITCODE
	if ($ExitCode -eq 1) {
		return @()
	}
	if ($ExitCode -ne 0) {
		throw "rg failed for pattern: $Pattern"
	}
	return @($Output)
}

function Assert-NoMatches {
	param(
		[string]$Label,
		[string[]]$Patterns,
		[string[]]$Roots
	)

	$Matches = @()
	foreach ($Pattern in $Patterns) {
		$Hits = Invoke-Rg -Pattern $Pattern -Roots $Roots
		foreach ($Hit in $Hits) {
			$Matches += "[$Label][$Pattern] $Hit"
		}
	}
	if ($Matches.Count -gt 0) {
		Write-Host "[LegacyGate] FAILED: $Label"
		$Matches | ForEach-Object { Write-Host $_ }
		throw "$Label matched retired entity model terms."
	}
	Write-Host "[LegacyGate] OK: $Label"
}

function Assert-ProjectileTemplateIdOnly {
	$Hits = Invoke-Rg -Pattern "\btemplate_id\b" -Roots $ScanRoots -Regex
	$Unexpected = @()
	foreach ($Hit in $Hits) {
		if ($Hit -match "projectile_template|ProjectileTemplate|PROJECTILE_TEMPLATE") {
			continue
		}
		$Unexpected += $Hit
	}
	if ($Unexpected.Count -gt 0) {
		Write-Host "[LegacyGate] FAILED: template_id allowlist"
		$Unexpected | ForEach-Object { Write-Host $_ }
		throw "template_id appeared outside ProjectileTemplate-related paths."
	}
	Write-Host "[LegacyGate] OK: template_id only appears in ProjectileTemplate-related paths"
}

function New-LegacyProbeScenario {
	param([string]$ProbePath)

	$ProbeDir = Split-Path -Parent $ProbePath
	New-Item -ItemType Directory -Path $ProbeDir -Force | Out-Null
	@'
[gd_resource type="Resource" script_class="BattleScenario" load_steps=4 format=3]

[ext_resource type="Script" path="res://scripts/battle/battle_scenario.gd" id="1_scenario"]
[ext_resource type="Script" path="res://scripts/battle/battle_spawn_entry.gd" id="2_spawn"]
[ext_resource type="Script" path="res://scripts/battle/battle_validation_rule.gd" id="3_rule"]

[sub_resource type="Resource" id="Spawn_rejected_legacy_fields"]
script = ExtResource("2_spawn")
archetype_id = &"archetype_basic_shooter"
lane_id = 0
x_position = 160.0
spawn_overrides = {
"entity_template_id": &"plant_basic_shooter",
"legacy_template_id": &"plant_basic_shooter"
}

[sub_resource type="Resource" id="Rule_protocol_issue"]
script = ExtResource("3_rule")
rule_id = &"legacy_fields_rejected"
description = "retired entity model fields must be rejected as unsupported spawn overrides"
event_name = &"protocol.issue"
min_count = 1

[sub_resource type="Resource" id="Rule_no_spawn"]
script = ExtResource("3_rule")
rule_id = &"legacy_fields_do_not_spawn"
description = "retired entity model field probe must not instantiate runtime entities"
event_name = &"entity.spawned"
min_count = 0
max_count = 0

[resource]
script = ExtResource("1_scenario")
scenario_id = &"legacy_entity_model_protocol_probe"
display_name = "Legacy Entity Model Protocol Probe"
description = "Temporary negative probe generated by tools/check_no_legacy_entity_model.ps1."
goals = PackedStringArray("Verify retired entity model fields are rejected by protocol validation.", "Verify the rejected probe does not spawn an entity.")
validation_time_limit = 0.4
validation_rules = [SubResource("Rule_protocol_issue"), SubResource("Rule_no_spawn")]
spawns = [SubResource("Spawn_rejected_legacy_fields")]
'@ | Set-Content -LiteralPath $ProbePath -Encoding UTF8
}

function Invoke-ProtocolProbe {
	if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
		$script:OutputRoot = Join-Path $ProjectRoot "artifacts\legacy_probe"
	}
	New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null

	$ProbeFile = Join-Path $OutputRoot "legacy_entity_model_protocol_probe.tres"
	New-LegacyProbeScenario -ProbePath $ProbeFile

	$RelativeProbe = [System.IO.Path]::GetRelativePath($ProjectRoot, $ProbeFile).Replace("\", "/")
	$ScenarioPath = "res://$RelativeProbe"
	$Result = & (Join-Path $PSScriptRoot "run_validation.ps1") `
		-Scenario $ScenarioPath `
		-GodotExe $GodotExe `
		-OutputRoot $OutputRoot `
		-RunLabel "legacy_entity_model_protocol_probe" `
		-PassThru

	if ($Result.Status -ne "passed") {
		Write-Host "[LegacyGate] FAILED: protocol probe"
		Write-Host "Probe scenario: $ScenarioPath"
		Write-Host "Run dir: $($Result.RunDir)"
		throw "Legacy entity model protocol probe failed."
	}
	Write-Host "[LegacyGate] OK: protocol probe rejected retired entity fields"
	Write-Host "[LegacyGate] Probe artifacts: $($Result.RunDir)"
}

$RetiredEntityTerms = @(
	"EntityTemplate",
	"TriggerBinding",
	"legacy_template_id",
	"backend_entity_template",
	"entity_template_id",
	"object_template_id",
	"protected_template_id",
	"source_template_id",
	"target_template_id",
	"target_template_ids"
)

$RetiredRuntimeTerms = @(
	"compiled_trigger_bindings",
	"build_runtime_triggers_from_bindings",
	"TriggerBindingRef"
)

Assert-NoMatches -Label "retired entity model terms" -Patterns $RetiredEntityTerms -Roots $ScanRoots
Assert-NoMatches -Label "retired runtime binding terms" -Patterns $RetiredRuntimeTerms -Roots $ScanRoots
Assert-ProjectileTemplateIdOnly

if (-not $SkipProtocolProbe) {
	Invoke-ProtocolProbe
} else {
	Write-Host "[LegacyGate] SKIP: protocol probe"
}

Write-Host "[LegacyGate] PASSED"
